PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "陈冰",
  "email": "isabella.chen@example.com",
  "address": "青岛市市南区香港中路376号颐和国际大厦",
  "dateOfBirth": "1987-10-17"
}
###